/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cl.duoc.prueba3.GUI;

import cl.duoc.prueba3.DTO.Cliente;
import cl.duoc.prueba3.DTO.Producto;
import cl.duoc.prueba3.DTO.Vendedor;
import cl.duoc.prueba3.Services.Implements.*;

/**
 *
 * @author sebas
 */
public class vwVenta extends javax.swing.JInternalFrame {
    
    listaVendedor listav;
    listaProducto listap;
    listaCliente listac;
    
    public vwVenta(listaVendedor listav, listaProducto listap, listaCliente listac) {
        initComponents();
        this.listav = listav;
        refrescarVendedor();
        this.listap = listap;
        refrescarProducto();
        this.listac = listac;
        refrescarCliente();
    }
    
    private void refrescarVendedor(){   
        comboVendedor.removeAllItems();
        for(Vendedor vendedor : this.listav.listar()){
            comboVendedor.addItem(vendedor.nombre);
        }
    }
    
    private void refrescarProducto(){   
    comboProducto.removeAllItems();
        for(Producto producto : this.listap.listar()){
            comboProducto.addItem(producto.getNombre());
        }
    }
    
    private void refrescarCliente(){   
    comboCliente.removeAllItems();
        for(Cliente cliente : this.listac.listar()){
            comboCliente.addItem(cliente.getNombre());
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantidadTxt = new javax.swing.JTextField();
        comboLitro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboVendedor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        refrescarV = new javax.swing.JButton();
        refrescarP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        refrescarC = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Realizar compra");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenido realize su compra");

        jLabel2.setText("Seleccione producto:");

        jLabel3.setText("Seleccione litros: ");

        jLabel4.setText("Cantidad:");

        comboLitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "500", "1", "2", "5", "10", "20" }));

        jLabel5.setText("Seleccione vendedor:");

        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        refrescarV.setText("Refrescar");
        refrescarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarVActionPerformed(evt);
            }
        });

        refrescarP.setText("Refrescar");
        refrescarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarPActionPerformed(evt);
            }
        });

        jLabel6.setText("Cliente:");

        refrescarC.setText("Refrescar");
        refrescarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidadTxt)
                                    .addComponent(comboVendedor, 0, 89, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboLitro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refrescarV)
                            .addComponent(refrescarP)
                            .addComponent(refrescarC, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refrescarC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refrescarP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboLitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refrescarV))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String comboV = String.valueOf(comboVendedor.getSelectedItem());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refrescarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarVActionPerformed
        // TODO add your handling code here:
        refrescarVendedor();
    }//GEN-LAST:event_refrescarVActionPerformed

    private void refrescarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarPActionPerformed
        // TODO add your handling code here:
        refrescarProducto();
    }//GEN-LAST:event_refrescarPActionPerformed

    private void refrescarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarCActionPerformed
        // TODO add your handling code here:
        refrescarCliente();
    }//GEN-LAST:event_refrescarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboLitro;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JComboBox<String> comboVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton refrescarC;
    private javax.swing.JButton refrescarP;
    private javax.swing.JButton refrescarV;
    // End of variables declaration//GEN-END:variables
}
