/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cl.duoc.prueba3.GUI;

import cl.duoc.prueba3.DTO.Cliente;
import cl.duoc.prueba3.DTO.Producto;
import cl.duoc.prueba3.DTO.Vendedor;
import cl.duoc.prueba3.DTO.Venta;
import cl.duoc.prueba3.Services.Implements.*;
import cl.duoc.prueba3.Utils.Validaciones;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class vwVenta extends javax.swing.JInternalFrame {
    Validaciones validar = new Validaciones();
    listaVendedor listav;
    listaProducto listap;
    listaCliente listac;
    listaVentas listVenta;
    
    public vwVenta(listaVendedor listav, listaProducto listap, listaCliente listac, listaVentas listVenta) {
        initComponents();
        this.listav = listav;
        refrescarVendedor();
        this.listap = listap;
        refrescarProducto();
        this.listac = listac;
        refrescarCliente();
        this.listVenta = listVenta;
    }
    
    private void refrescarVendedor(){   
    comboVendedor.removeAllItems();
        for(Vendedor vendedor : this.listav.listar()){
            comboVendedor.addItem(vendedor.nombre);
        }
    }
    
    private void refrescarProducto(){   
    comboProducto.removeAllItems();
        for(Producto producto : this.listap.listar()){
            comboProducto.addItem(producto.getNombre());
        }
    }
    
    private void refrescarCliente(){   
    comboCliente.removeAllItems();
        for(Cliente cliente : this.listac.listar()){
            comboCliente.addItem(cliente.getNombre());
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantidadTxt = new javax.swing.JTextField();
        comboLitro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboVendedor = new javax.swing.JComboBox<>();
        botonComprar = new javax.swing.JButton();
        refrescarV = new javax.swing.JButton();
        refrescarP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        refrescarC = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaObservacion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        labelPago = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Realizar compra");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Bienvenido realize su compra");

        jLabel2.setText("Seleccione producto:");

        jLabel3.setText("Seleccione litros: ");

        jLabel4.setText("Cantidad:");

        comboLitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "500", "1", "2", "5", "10", "20" }));

        jLabel5.setText("Seleccione vendedor:");

        botonComprar.setText("Comprar");
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });

        refrescarV.setText("Refrescar");
        refrescarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarVActionPerformed(evt);
            }
        });

        refrescarP.setText("Refrescar");
        refrescarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarPActionPerformed(evt);
            }
        });

        jLabel6.setText("Cliente:");

        refrescarC.setText("Refrescar");
        refrescarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarCActionPerformed(evt);
            }
        });

        jLabel7.setText("Observaciones:");

        areaObservacion.setColumns(20);
        areaObservacion.setRows(5);
        jScrollPane1.setViewportView(areaObservacion);

        jLabel8.setText("Seleccione fecha de entrega:");

        fechaTxt.setText("dd-mm-yyyy");

        jLabel9.setText("Total a pagar:");

        labelPago.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidadTxt)
                                    .addComponent(comboVendedor, 0, 89, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboLitro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refrescarV)
                            .addComponent(refrescarP)
                            .addComponent(refrescarC, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabel7)
                    .addComponent(botonComprar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPago)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refrescarC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refrescarP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboLitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refrescarV))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(botonComprar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int calcularTotal(){
        int productoIdx = comboProducto.getSelectedIndex();
        int cantidad = Integer.parseInt(cantidadTxt.getText());
        Producto producto = listap.getProductoIdx(productoIdx);
        return cantidad * producto.getPrecio();
    }
    
    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        // TODO add your handling code here:
        try{
            String cliente = String.valueOf(comboCliente.getSelectedItem());
            String producto = String.valueOf(comboProducto.getSelectedItem());
            int litros = Integer.parseInt(String.valueOf(comboLitro.getSelectedItem()));
            int cantidad = Integer.parseInt(cantidadTxt.getText());
            String vendedor = String.valueOf(comboVendedor.getSelectedItem());
            String obs = areaObservacion.getText();
            LocalDate fechaEntrega = validar.formatearFecha(fechaTxt.getText());
            
            if(cantidad > 0 && !producto.trim().isEmpty() && !cliente.trim().isEmpty() && !vendedor.trim().isEmpty()){
                Venta venta = new Venta();
                venta.setCliente(cliente);
                venta.setProducto(producto);
                venta.setLiros(litros);
                venta.setCantidad(cantidad);
                venta.setVendedor(vendedor);
                venta.setObervaciones(obs);
                venta.setFechaEntrega(fechaEntrega);
                venta.setFechaVenta(LocalDate.now());
                venta.setTotalPago(calcularTotal());
                labelPago.setText(String.valueOf(calcularTotal()));
                listVenta.agregarVenta(venta);
                JOptionPane.showMessageDialog(null, "Compra realizada con exito");
            }else{
                JOptionPane.showMessageDialog(null, "Ingrese datos correctos");
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_botonComprarActionPerformed

    private void refrescarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarVActionPerformed
        // TODO add your handling code here:
        refrescarVendedor();
    }//GEN-LAST:event_refrescarVActionPerformed

    private void refrescarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarPActionPerformed
        // TODO add your handling code here:
        refrescarProducto();
    }//GEN-LAST:event_refrescarPActionPerformed

    private void refrescarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarCActionPerformed
        // TODO add your handling code here:
        refrescarCliente();
    }//GEN-LAST:event_refrescarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaObservacion;
    private javax.swing.JButton botonComprar;
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboLitro;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JComboBox<String> comboVendedor;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPago;
    private javax.swing.JButton refrescarC;
    private javax.swing.JButton refrescarP;
    private javax.swing.JButton refrescarV;
    // End of variables declaration//GEN-END:variables
}
